name: NFL Data Pipeline

# Run automatically every Tuesday at 8:00 AM UTC (3:00 AM EST)
# Also allow running manually from the "Actions" tab
on:
  schedule:
    - cron: '0 8 * * 2' 
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      # 1. Download the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install Libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    #   # 4. Run the Scraper & Loader
    #   - name: Run ETL Pipeline
    #     env:
    #       DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #     run: |
    #       export PYTHONPATH=$PYTHONPATH:$(pwd)/backend
    #       python -m backend.etl.run_etl

      # 5. Run the Aggregations
      - name: Run Aggregations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/backend
          python -m backend.etl.aggregate